---
- hosts: webserver
  vars:
    github_org: okfn
    repo: ckanext-glasgow
    version: master
  tasks:
    - name: Checkout version
      action: git repo=https://github.com/{{ github_org }}/{{ repo }} dest=/usr/lib/ckan/default/src/{{ repo }} version={{ version }} force=yes

    - name: Pull code
      action: command chdir=/usr/lib/ckan/default/src/{{ repo }}/ git pull
      register: update

    - name: Restart Supervisor for harvest-fetch
      supervisorctl: name=harvest-fetch:* state=restarted

    - name: Restart Supervisor for harvest-gather
      supervisorctl: name=harvest-gather state=restarted

    - name: Reload apache
      action: service name=apache2 state=reloaded
      when: update.changed
